project_id = "rinbam"

[api]
port = 55421

[db]
port = 55422
shadow_port = 55420
major_version = 17

[db.pooler]
port = 55429

[studio]
port = 55423

[inbucket]
port = 55424

[analytics]
port = 55427
